version: '3'

services:
    mongo:
        image: mongo
        ports:
            - "27017:27017"
        networks:
            - mongo-compose-network

    go-api:
        image: go-rest-api
        ports: 
            - "8080:8080"
        networks: 
            - mongo-compose-network
        depends_on: 
            - mongo

networks: 
    mongo-compose-network:
        driver: bridge
